# Generated by Django 4.1.7 on 2023-03-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ceo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('salary', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_domain', models.CharField(max_length=50)),
                ('company_revenue', models.CharField(max_length=50)),
                ('company_headoffice', models.CharField(max_length=50)),
                ('ceo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.ceo')),
            ],
        ),
    ]
